create table property (
    id uuid generated by default as identity primary key,
    type text,
    address_id not null references public.address,
    sq_footage text,
    no_of_bedrooms text,
    no_of_bathrooms text,
    owner_id not null references public.owner,
    rental_price text,
    status text,
    lease_start_date text,
    lease_end_date text,
)


create table address (
    address_id generated by default as identity primary key,
    street text,
    city text,
    state text,
    postal_code text,
    country text,
)

create table owner (
    owner_id generated by default as identity primary key,
    name text,
    phone text,
    email text,
    owner_type text,
    company_name text,
    contact_preference text,
)

create table userinfo (
  id bigint generated always as identity primary key,
  email text,
  name text,
  role text,
  user_id uuid references "auth"."users"
);

-- enabling row level security.
alter table property enable row level security;
alter table address enable row level security;
alter table owner enable row level security;
alter table userinfo enable row level security;

-- creating policies
create policy "Enable insert on property table for authenticated users"
on "public"."property"
to authenticated
with check (
  true
);

create policy "Enable insert on address table for authenticated users"
on "public"."address"
to authenticated
with check (
  true
);

create policy "Enable insert on owner table for authenticated users"
on "public"."owner"
to authenticated
with check (
  true
);

create policy "Enable insert on userinfo table for authenticated users"
on "public"."userinfo"
to authenticated
with check (
  true
);
